services:
    little_url_postgres:
        image: postgres
        container_name: little_url_postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql
        networks:
            - network

    # little_url_api:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: little_url_api
    #     environment:
    #         DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?schema=public"
    #         PRISMA_MIGRATE_SKIP_CREATE_DATABASE: "true"
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - postgres
    #     networks:
    #         - network
    #     command: >
    #         bash -c "npm run prisma:migrate && npm run dev"

networks:
    network:
        driver: bridge

volumes:
    postgres:
        driver: local
