POST http://localhost:3000/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTNiYmNhMC0wNzk0LTRkMDUtYjk5OS03YjNiNGJlNjg4NDciLCJpYXQiOjE3MjM0MDM2NzEsImV4cCI6MTcyMzQwNzI3MX0.sndnpSH4zVc4hobVOTaOBpcu_MU8Ctcgszg7jgaK_Gk

