POST http://localhost:3000/urls
# POST https://little-url.alexgalhardo.com/urls
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWY4YjdiYS03ZTE5LTQzNjYtYTU1ZS01ZDE5NTIyZTRiODgiLCJpYXQiOjE3MzgwMDE1MjAsImV4cCI6MTczODAwNTEyMH0.zyDPJ2CMh_FYPKRf8rmcAA3ue6WlZsRp2d7BX6XXok0

{
	"url": "https://microsoft.com"
}
