# PATCH http://localhost:3000/urls/55c6a144-7d3e-4d62-960a-42b4bcc12ebe
PATCH https://little-url.alexgalhardo.com/urls/55c6a144-7d3e-4d62-960a-42b4bcc12ebe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxY2JiM2ZkYS1jMmExLTQ3YmMtODI0NC0wMTZjZTlmYjlhYzkiLCJpYXQiOjE3MjM0NzE0MjAsImV4cCI6MTcyMzQ3NTAyMH0.i7vi7GDCS7Y6t17fD3RERc9NaXXArMIGkIpIbe7M2ss

{
	"origin": "https://test.com"
}
