GET http://localhost:3000/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTNiYmNhMC0wNzk0LTRkMDUtYjk5OS03YjNiNGJlNjg4NDciLCJpYXQiOjE3MjM0MDUwNDAsImV4cCI6MTcyMzQwODY0MH0.8Xcc81-pVQ7np3Zd3awrzuMheNuZhjBoFhzjz22-FqA
